name: "Bug Report"
description: "Create a report to help us improve."
labels: [Bug]
body:
- type: textarea
  attributes:
    label: "Describe The Bug"
    description: "A clear and concise description of what you're experiencing."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Steps To Reproduce"
    description: "Steps to reproduce the behavior."
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: "Expected Behavior"
    description: "A clear and concise description of what you expected to happen."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Screenshots"
    description: "If applicable, add screenshots to help explain your problem."
    placeholder: "Drag and drop the screenshots into this box."
  validations:
    required: false
- type: textarea
  attributes:
    label: "Device Information"
    description: "Device information should be listed."
    placeholder: |
      1. Device: [e.g. Redmi Note 10 Pro]
      2. OS: [e.g. LineageOS]
      3. Version: [e.g. 13.0.0]
      4. Platform: [e.g. arm64]
  validations:
    required: true
- type: textarea
  attributes:
    label: "Attach ADB Logs"
    description: "Connect your phone to a computer and run `adb logcat > issue.log`."
    placeholder: "Drag and drop the log file into this box."
  validations:
    required: false
- type: textarea
  attributes:
    label: "Additional Context"
    description: "Anything that will give us more context about the issue you are encountering!"
  validations:
    required: false
- type: checkboxes
  attributes:
    label: "Checklist"
    description: "Your issue will be closed if you haven't done these steps."
    options: 
      - label: "All required information is present"
        required: true
      - label: "I'm running latest version available on bitgapps.github.io"
        required: true
      - label: "I have written a short but informative title"
        required: true
      - label: "I have searched the existing issues before reporting"
        required: true
