blank_issues_enabled: false
contact_links:
  - name: XDA Community Support
    url: https://forum.xda-developers.com/t/custom-gapps-bitgapps-for-android.4012165
    about: Please ask and answer questions here.
