name: ADDON

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    if: github.repository_owner == 'BiTGApps'
    runs-on: ubuntu-latest

    steps:
       - name: Initial Setup
         uses: actions/checkout@v3

       - name: Create BiTGApps
         run: |
           rm -rf BiTGApps
           mkdir BiTGApps

       - name: Clone Build Sources
         run: |
           git clone https://github.com/BiTGApps/BiTGApps BiTGApps

       - name: Create Sources
         run: |
           mkdir BiTGApps/addons/sources

       - name: Clone Package Sources
         run: |
           git clone https://github.com/BiTGApps/addon-sources BiTGApps/addons/sources/addon-sources

       - name: Github Release CLI
         run: |
           npm install -g github-release-cli

       - name: Build BiTGApps Package
         run: |
           cd BiTGApps/addons
           install -d build out
           . scripts/envsetup.sh
           . scripts/build.sh all
           . scripts/core.sh arm ARM
           . scripts/core.sh arm64 ARM64
           cd ../..

       - name: Cleanup
         run: |
           rm -rf BiTGApps
