name: BASIC

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    if: github.repository_owner == 'BiTGApps'
    runs-on: ubuntu-latest

    steps:
       - name: Initial Setup
         uses: actions/checkout@v3

       - name: Create BiTGApps
         run: |
           rm -rf BiTGApps
           mkdir BiTGApps

       - name: Clone Build Sources
         run: |
           git clone https://github.com/BiTGApps/BiTGApps BiTGApps

       - name: Create Sources
         run: |
           mkdir BiTGApps/sources

       - name: Clone Package Sources
         run: |
           git clone https://github.com/BiTGApps/arm-sources BiTGApps/sources/arm-sources
           git clone https://github.com/BiTGApps/arm64-sources BiTGApps/sources/arm64-sources
           git clone https://github.com/BiTGApps/common-sources BiTGApps/sources/common-sources
           git clone https://github.com/BiTGApps/addon-sources BiTGApps/sources/addon-sources

       - name: Build BiTGApps Package
         run: |
           cd BiTGApps
           . envsetup.sh MINI
           make
           cd ..

       - name: Github Release CLI
         run: |
           npm install -g github-release-cli

       - name: Upload Build Artifact
         run: |
           cd BiTGApps
           . envsetup.sh MINI
           . release.sh arm
           . release.sh arm64
           cd ..

       - name: Cleanup
         run: |
           rm -rf BiTGApps
